"""change collections name to list

Revision ID: c2da75e995fc
Revises: 
Create Date: 2018-12-17 19:10:00.873465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2da75e995fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection')
    op.drop_table('user_collections')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_collections',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('list_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['collection.id'], name='user_collections_list_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='user_collections_user_id_fkey')
    )
    op.create_table('collection',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('place_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='collection_pkey')
    )
    # ### end Alembic commands ###
